services:

  mysql:
    image: mysql:8
    container_name: mysql-devops
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsdb

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - devops-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  backend:
    build: .
    container_name: backend-devops
    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    networks:
      - devops-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/tareas"]
      interval: 30s
      timeout: 10s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  mysql_data:

networks:
  devops-network: