version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-devops
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsdb
    ports:
      - "3307:3306"

  backend:
    build: .
    container_name: backend-devops
    ports:
      - "8080:8080"
    depends_on:
      - mysql